spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Gers_Garage
        username: postgres
        password: Caio6021
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
